# Creare la cartella <jupyter-notebook> (conterra' tutti i file del notebook)

version:                "3"
services:
  datascience-notebook:
      image:            jupyter/datascience-notebook
      volumes:
        - ./jupyter-notebook/:/home/jovyan/work
      ports:
        - 8888:8888
      container_name:   datascience-notebook-container
